name: Part 3 CI test
on:
  push:
    branches:
      - part3
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: maven
    - name: Build project
      run: mvn clean install -DskipTests -pl byte-buddy-dep -am

        
